      
---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
     - name: Install passwd package
       apt:
          name: passwd
          state: present
       when:  ansible_distribution not in "Debian, Ubuntu"
       tags:
         - app1
     - name: create group
       group:
          name: cloudteam
          state: present
#       when: ansible_distribution_major_version < 9
     - name: Create user
       user:
          name: richessill2023
          comment: Rich Admin
          group: cloudteam

- hosts: database
  become: yes
  tasks:
     - name: install apache
       apt: 
         name: apache2
         state: present
     - name: Start apache service
       service: name=apache2 state=started enabled=yes
       tags:
         - service
         